### ISSUE TITLE
Problem during installation 

### ISSUE THREAD

**Issue by sergeybe** [lk-geimfari/elizabeth#113]
Error message:
```
$ pip install elizabeth
Collecting elizabeth
  Using cached elizabeth-0.3.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lElGl2/elizabeth/setup.py", line 3, in <module>
        import elizabeth
      File "elizabeth/__init__.py", line 27, in <module>
        from elizabeth.core import *
      File "elizabeth/core/__init__.py", line 1, in <module>
        from .elizabeth import (
      File "elizabeth/core/elizabeth.py", line 38, in <module>
        from . import interdata as common
      File "elizabeth/core/interdata/__init__.py", line 5, in <module>
        from .code import *
      File "elizabeth/core/interdata/code.py", line 56
    SyntaxError: Non-ASCII character '\xc4' in file elizabeth/core/interdata/code.py on line 56, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
I suggest `encoding: utf-8` was forgotten in comment at first line.

**Comment by lk-geimfari** [comment]
@sergeybe Which version of Python do you use?

**Comment by sergeybe** [comment]
My version:
```
$ python
Python 2.7.12 (default, Nov 21 2016, 21:09:09)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by lk-geimfari** [comment]
@sergeybe That's right. Elizabeth run only on Python 3.x.

**Comment by lk-geimfari** [comment]
@sergeybe Look on the badges in the top of README.md.

**Comment by lk-geimfari** [comment]
Do you have any problems with `Python 3.x`? Can i close this issue?
