### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by mfeitoza** [lk-geimfari/elizabeth#123]
```python
Collecting elizabeth
  Using cached elizabeth-0.3.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5xf3_d/elizabeth/setup.py", line 3, in <module>
        from elizabeth import __version__, \
      File "elizabeth/__init__.py", line 25, in <module>
        from elizabeth.core import *
      File "elizabeth/core/__init__.py", line 1, in <module>
        from elizabeth.core.providers import (
      File "elizabeth/core/providers.py", line 34, in <module>
        from elizabeth.core import interdata as common
      File "elizabeth/core/interdata/__init__.py", line 16
    SyntaxError: Non-ASCII character '\xd0' in file elizabeth/core/interdata/__init__.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5xf3_d/elizabeth/
```

I get this error when i try install elizabeth both in venv or global.

**Comment by lk-geimfari** [comment]
#113

**Comment by lk-geimfari** [comment]
@mfeitoza Any problems with `Python 3.x?`

**Comment by mfeitoza** [comment]
My mistake, elizabeth is not compatible with 2.7 right?
