### ISSUE TITLE
Attempting install, getting SyntaxError Non-ASCII character error

### ISSUE THREAD

**Issue by mdublin** [lk-geimfari/elizabeth#73]
On Mac OSX 10.12.2 using zsh, I run: 

`$ pip install elizabeth`

And get the following error message:

```
Collecting elizabeth
  Using cached elizabeth-0.3.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vg/c9ncn1fs5xzdqccf9mxf24vr0000gn/T/pip-build-lnl_QD/elizabeth/setup.py", line 3, in <module>
        import elizabeth
      File "elizabeth/__init__.py", line 10, in <module>
        from elizabeth.core import *
      File "elizabeth/core/__init__.py", line 1, in <module>
        from .elizabeth import (
      File "elizabeth/core/elizabeth.py", line 35, in <module>
        from . import interdata as common
      File "elizabeth/core/interdata.py", line 720
    SyntaxError: Non-ASCII character '\xe2' in file elizabeth/core/interdata.py on line 720, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vg/c9ncn1fs5xzdqccf9mxf24vr0000gn/T/pip-build-lnl_QD/elizabeth/
```

**Comment by lk-geimfari** [comment]
@mdublin You're tried run it on Python 2. Elizabeth works only on Python 3.
